# Generated by Django 5.0.1 on 2024-01-26 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_enrollment_course_students_lesson_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='is_complete',
        ),
    ]
