# Generated by Django 5.0.1 on 2024-02-18 18:48

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_lesson_options_alter_lesson_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.JSONField(validators=[api.models.LessonValidator()]),
        ),
    ]
